# Generated by Django 4.0.4 on 2022-05-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('record_2006', models.FloatField(blank=True, null=True)),
                ('record_2007', models.FloatField(blank=True, null=True)),
                ('record_2004', models.FloatField(blank=True, null=True)),
                ('record_2005', models.FloatField(blank=True, null=True)),
                ('record_2008', models.FloatField(blank=True, null=True)),
                ('record_2009', models.FloatField(blank=True, null=True)),
                ('record_2011', models.FloatField(blank=True, null=True)),
                ('record_2010', models.FloatField(blank=True, null=True)),
                ('record_2013', models.FloatField(blank=True, null=True)),
                ('record_2012', models.FloatField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorldBank.metric')),
            ],
        ),
    ]
